name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:

  deployment-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: echo "Deploying to dev"

  deployment-stg:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: deploy
        run: echo "Deploying to stg"

  deployment-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo "Deploying to prod"
