  name: GitHub Actions Demo
  run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
  on: [push]

  jobs:
    extract-team-name:
      runs-on: ubuntu-latest
      outputs:
        team-name: ${{ steps.extract-team-name.outputs.team-name }}
      steps:
        - name: extract-team-name
          env:
            BRANCH: ${{ github.ref_name }}
          id: extract-team-name
          run: echo "team-name=${BRANCH%%/*}" >> $GITHUB_OUTPUT


    deployment-team:
      runs-on: ubuntu-latest
      environment:  ${{ needs.extract-team-name.outputs.team-name }}
      needs: extract-team-name
      steps:
        - name: deploy
          run: echo "Deploying to ${{ needs.extract-team-name.outputs.team-name }}"
    deployment-eil:
      runs-on: ubuntu-latest
      needs: deployment-team
      environment: eil
      steps:
        - name: deploy
          run: echo "Deploying to eil"

    deployment-qa:
      runs-on: ubuntu-latest
      environment: qa
      needs: deployment-eil
      steps:
        - name: deploy
          run: echo "Deploying to qa"

    deployment-prod:
      runs-on: ubuntu-latest
      environment: stg
      needs: deployment-qa
      steps:
        - name: deploy
          run: echo "Deploying to stg"
