name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  deployment-team:
    runs-on: ubuntu-latest
    environment: ${{ github.head_ref.split('/')[0] }}
    steps:
      - name: deploy
        run: echo "Deploying to ${{ github.head_ref.split('/')[0] }}"

  deployment-eil:
    runs-on: ubuntu-latest
    needs: deployment-team
    environment: eil
    steps:
      - name: deploy
        run: echo "Deploying to eil"

  deployment-qa:
    runs-on: ubuntu-latest
    environment: qa
    needs: deployment-dev
    steps:
      - name: deploy
        run: echo "Deploying to qa"

  deployment-prod:
    runs-on: ubuntu-latest
    environment: stg
    needs: deployment-qa
    steps:
      - name: deploy
        run: echo "Deploying to stg"
